//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CodeText {
            get {
                object obj = ResourceManager.GetObject("CodeText", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compiled {
            get {
                object obj = ResourceManager.GetObject("compiled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compiled_dark {
            get {
                object obj = ResourceManager.GetObject("compiled_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream CompileError {
            get {
                return ResourceManager.GetStream("CompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Back {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Code {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_CollapseFolders {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_CollapseFolders", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Comment {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Compile {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Compile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_CreateProcedure {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_CreateProcedure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Dialog {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Dialog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Find {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_FoldUnfold {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_FoldUnfold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Forward {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_GoDefinitions {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_GoDefinitions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Goto {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Goto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Help {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Include {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Include", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Indent {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Indent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_List {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_List", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_New {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Open {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Options {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Outline {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_OutputPane {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_OutputPane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_QuickTips {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_QuickTips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Redo {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_RefreshParser {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_RefreshParser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Save {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_SaveAll {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_SaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_ScriptListAdd {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_ScriptListAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_ScriptListFind {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_ScriptListFind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_ScriptListFindNext {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_ScriptListFindNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_ScriptListFindPrevious {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_ScriptListFindPrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_ScriptListRemove {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_ScriptListRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_ScriptListSaved {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_ScriptListSaved", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_ScriptListUnsaved {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_ScriptListUnsaved", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_SplitDocument {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_SplitDocument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkToolbar_Undo {
            get {
                object obj = ResourceManager.GetObject("DarkToolbar_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream DontFind {
            get {
                return ResourceManager.GetStream("DontFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FoldUnfoldLight {
            get {
                object obj = ResourceManager.GetObject("FoldUnfoldLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeepWindowOff {
            get {
                object obj = ResourceManager.GetObject("KeepWindowOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeepWindowOn {
            get {
                object obj = ResourceManager.GetObject("KeepWindowOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macros {
            get {
                object obj = ResourceManager.GetObject("macros", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*******************************************************************************
        ///        Name: 
        ///        Location: 
        ///        Description: 
        ///
        ///            Created: sFall Script Editor
        ///            Updated: 
        ///*******************************************************************************/
        ///
        ////* Include Files */
        /////#include &quot;define.h&quot;
        /////#include &quot;command.h&quot;
        ///
        ////* Defines */
        ///
        ///
        ////* Script Procedures */
        ///procedure start;
        ///
        ///
        ////* Local Variables which are saved. All Local Variables need to be prepended by LVAR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newScript {
            get {
                return ResourceManager.GetString("newScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap opcode {
            get {
                object obj = ResourceManager.GetObject("opcode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap procedure {
            get {
                object obj = ResourceManager.GetObject("procedure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SyntaxDefinition name = &quot;UserWords&quot;&gt;
        ///
        ///  &lt;KeyWords name = &quot;SpecMacros&quot; bold=&quot;true&quot; italic=&quot;false&quot; bgcolor=&quot;DimGray&quot; color=&quot;White&quot;&gt;
        ///    &lt;Key word = &quot;DEBUGMSG&quot; /&gt;
        ///  &lt;/KeyWords&gt;
        ///  
        ///  &lt;KeyWords name = &quot;UserMacros&quot; bold=&quot;true&quot; italic=&quot;false&quot; color=&quot;Green&quot;&gt;
        ///    &lt;Key word = &quot;&quot; /&gt;
        ///  &lt;/KeyWords&gt;
        ///  
        ///&lt;/SyntaxDefinition&gt;
        ///.
        /// </summary>
        internal static string User_SyntaxRules {
            get {
                return ResourceManager.GetString("User_SyntaxRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // The file contains a description of the user functions.
        /////
        ///// Structure:
        ///// &quot;function name&quot;&lt;d&gt;&quot;short description of the function&quot;&lt;s&gt;&quot;code that will be inserted into the script&quot;&lt;cr&gt;
        ///// &lt;m&gt; &quot;node name menu&quot;
        ///// &lt;m+&gt; &quot;name for sub node&quot;
        ///// &lt;m-&gt; close menu node.
        ///// &lt;-&gt; delimiter (only for the top level)
        ///// &lt;cr&gt; carriage return to a new line (optional)
        ///// 
        ///// In the &quot;Menu Node&quot;, &quot;function name&quot;, &quot;short description of the function&quot; and
        ///// &quot;code that will be inserted into the script&quot; can contain any ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserFunctions {
            get {
                return ResourceManager.GetString("UserFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap variable {
            get {
                object obj = ResourceManager.GetObject("variable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
